int main(int argc, char* argv[]);
void init3DSurfaceWindow();
void reshape3D(int w, int h);
void display3D();
void drawGround();
void initVBO();
void drawQuads();
void mouseScrollWheelHandler3D(int button, int dir, int xMouse, int yMouse);
void mouseMotionHandler3D(int x, int y);
void keyboardHandler3D(unsigned char key, int x, int y);
//void specialKeyHandler(int key, int x, int y);
void animationHandler(int param);